### ISSUE TITLE
Define Arquillian Cube version and bom in the parent

### ISSUE THREAD

**Issue by cescoffier** [openshiftio/booster-parent#13]

**Comment by Ladicek** [comment]
If the BOM is imported in booster-parent, will it take precedence over BOMs imported in individual boosters? This might possibly affect dependency resolution in an unexpected way.

**Comment by cescoffier** [comment]
If you want a different version, updating the `arquillian-cube.version` property in the child pom will change it.

**Comment by Ladicek** [comment]
I'm thinking more about this situation: if the Cube BOM is imported in a parent POM, it will (I think?) have precedence over project/product BOMs imported in booster POMs. If these two BOMs declare (or bring transitively) the same dependency, the Cube BOM will now win over the project/product BOM (I think?), which probably isn't what we want.

CC @heiko-braun @kenfinnigan because in Swarm, we had a fair share of this kind of issues.

**Comment by cescoffier** [comment]
A BOM is just a placeholder when the "dependencyManagement" from the bom pom.xml file are "copied". 

what you describe is a dependency conflict issue. In this case, the only way to workaround it is to define the dependency as top-level dependency in your pom.xml file.

**Comment by Ladicek** [comment]
Indeed -- and in Swarm boosters, I was careful enough to import the Arq Cube BOM _after_ importing the Swarm BOM, so that Swarm-managed versions win over Cube-managed ones. With this change, it will be the opposite (I think?), and that's IMHO an issue in and of itself.

**Comment by cescoffier** [comment]
it's an issue with a known workaround (which is the one recommended by Maven). 

BTW, did you try to keep the bom defined in the booster itself. Just to see if it fixes the issue.

**Comment by Ladicek** [comment]
I didn't. In fact, I'm just speculating here -- I don't know if there's any conflict in any of the boosters :-) Just stating that this change can have a significant impact.

(Ideally, I'd love to get rid of booster-parent and have all the boosters self-contained, just like JBoss quickstarts have been doing. Yes, I understand the downsides.)

**Comment by cescoffier** [comment]
The booster maintainer can decide to get rid of the parent and copy the content in its pom.xml file. There is no problem with that - except having a pom.xml file containing several hundred lines.
