### ISSUE TITLE
Specify the version to be used for the openjdk-1.8-s2i image

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/booster-parent#20]
As the S2I Build process relies on a specific version of the openjdk-1.8 docker image [1], then such version info should also be included within `fabric8.generator.from` [2]

Proposition : 
```
<fabric8.generator.from>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2-7</fabric8.generator.from>
```

[1] https://access.redhat.com/containers/?tab=security#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift/images/1.2-7
[2] https://github.com/openshiftio/booster-parent/blob/master/pom.xml#L60

**Comment by cescoffier** [comment]
+1. Which version do we want to rely on at the moment?

**Comment by cmoulliard** [comment]
> moment

should be the latest `1.2-7` which contains `CVEs` and `CLOUD fixes` [1]

[1] - https://access.redhat.com/containers/?tab=changeSummary&scrollTo=imageAdvisory#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift/images/1.2-7

**Comment by Ladicek** [comment]
+1, though it adds yet another requirement to track and manage changes :-)

**Comment by cmoulliard** [comment]
> changes

This is the price to pay to deliver `quality` around technology, product

**Comment by Ladicek** [comment]
Well I agree :-) At the same time, this goes directly against continuous delivery of incremental improvements. Who could we ask about the recommended way of consuming this image (and similar "base" images)?

**Comment by cmoulliard** [comment]
As the boosters references this parent pom which contains also specific versions of f-m-p, k8s client, k8s java model, ... then the same question applies also for these libs. Which ones should be the one to be recommended for the end user, customer, .... Without such info, it is difficult and very hard for a company to qualify/certify  a technology and sell it internally.

**Comment by cescoffier** [comment]
Where do we stand on this one? 

Should I just update the property to:

```
<fabric8.generator.from>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2-7</fabric8.generator.from>
```

**Comment by cescoffier** [comment]
Ping @cmoulliard @Ladicek

**Comment by Ladicek** [comment]
I'm ambivalent on this. I guess it's something like +0 from me :-)

**Comment by cescoffier** [comment]
After discussion we decided to go for:

<fabric8.generator.from>registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2</fabric8.generator.from>

The `1.2` tag is updated to the latest build number and it should be "backward" compatible.
