### ISSUE TITLE
set fabric8.openshift.trimImageInContainerSpec to true by default?

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/booster-parent#23]
With the upgrade of Fabric8 Maven plugin to version 3.5.35, should we maybe set `fabric8.openshift.trimImageInContainerSpec` to `true` by default in the parent POM? It works around the OpenShift 3.7 app redeploy problem, per https://github.com/fabric8io/fabric8-maven-plugin/issues/1130#issuecomment-366216830.

This would allow boosters to run on OpenShift 3.7 without changes.

(Yes, I understand someone thought it's enough to update to FPM 3.5.35. My current understanding is that it's not; you need to add that system property too.)

CC @metacosm @geoand @cescoffier

**Comment by cescoffier** [comment]
What is not clear to me is the effect of this parameter on OpenShift 3.6. Do you have an idea?

**Comment by Ladicek** [comment]
Good point. I'll check.

**Comment by cescoffier** [comment]
what's also unclear is that redeploy is working for me without the property... is it due to the image size?

**Comment by Ladicek** [comment]
If I tried with Minishift, and without the property, I didn't experience image pull errors, but the deployment got cancelled, second deployment was started and only that succeeded. With the property, it works on the first try.

**Comment by metacosm** [comment]
Which versions of OpenShift are we supposed to support, anyway? :)
Online is on 3.7 so shouldn't that be our cut-off version?

**Comment by cescoffier** [comment]
I believe we still need to support 3.6.

**Comment by Ladicek** [comment]
Using the property seems to work fine with OpenShift 3.6 (tried with Minishift), but just to be sure, I also asked here: https://github.com/fabric8io/fabric8-maven-plugin/issues/1130#issuecomment-371198887

**Comment by metacosm** [comment]
Looks like it's confirmed that it works fine on OpenShift 3.6 so should we update `booster-parent`?

**Comment by cescoffier** [comment]
👍

**Comment by Ladicek** [comment]
Nice! If we're in the mood, could you please take a look at  https://github.com/openshiftio/booster-parent/issues/22 too? :-)

**Comment by cescoffier** [comment]
@Ladicek just because it's you ;-)

**Comment by metacosm** [comment]
It looks that this property is not needed anymore, either.

**Comment by Ladicek** [comment]
It does work around an issue in OpenShift Origin 3.7.0 / 3.7.1 and some OCP 3.7.x versions. The issue was fixed in Origin 3.7.2 (didn't check, but I believe their release notes :-) ) and in some OCP 3.7.x. I think we should figure out what the OCP 3.7.x fix version is and keep a note in RN for a while.
