### ISSUE TITLE
update fabric8 maven plugin for OSIO boosters

### ISSUE THREAD

**Issue by hrishin** [openshiftio/booster-parent#25]
In the context of [openshift.io application deployment](https://github.com/openshiftio/openshift.io/issues/2505#issuecomment-371732158) an important [issue (#1226)](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/CHANGELOG.md) has been fixed in the recent release of fabric8 maven plugin (FMP).
Need to update FMP dependency to v3.5.38  for openshift.io boosters accordingly.

**Comment by cescoffier** [comment]
Can you open a PR? I will be happy to apply it and release the parent.

**Comment by cescoffier** [comment]
The PR has been merged, and the version 20 of the booster parent has been updated. I'm updating the Vert.x booster (they are updated) - running the final tests and cutting a release of them.

**Comment by hrishin** [comment]
@cescoffier thats great! thanks
