### ISSUE TITLE
Upgrade FMP version to 3.5.40

### ISSUE THREAD

**Issue by piyush-garg** [openshiftio/booster-parent#29]
Right now, booster parent is using FMP 3.5.38, we should upgrade it to latest FMP version 3.5.40. I can send a patch for the same but not aware of the way how to test that new version is compatible with all the boosters and all are working fine.

@cescoffier Can you please guide?

**Comment by cescoffier** [comment]
I just use the vert.x booster to tests (I should extend my testing). So basically, I update the version, takes the boosters and update the booster parent. Then, I just run `mvn clean verify -Popenshift,openshift-it` on 2 versions of OpenShift (current and previous). It's far from being perfect but it detects basic failures.

**Comment by cescoffier** [comment]
@piyush1594 if you submit a PR, I would be happy to merge and release.

**Comment by cescoffier** [comment]
PR merged, release on its way.

**Comment by piyush-garg** [comment]
@cescoffier How much it will take to release the booster also with 3.5.40 FMP version and reflect that here https://github.com/fabric8-launcher/launcher-booster-catalog

Because we need them for OSIO with FMP 3.5.40

**Comment by Ladicek** [comment]
This take effort of multiple people. The Thorntail (née WildFly Swarm) _community_ boosters will be updated to the latest booster parent this week / next week (tracked here: https://issues.jboss.org/browse/THORN-2076). The product ones -- I'm not aware of any plans. I'm also not aware of other runtimes' plans. Feel free to get in touch with the wide RHOAR team :-)

**Comment by cescoffier** [comment]
@piyush1594 As said by @Ladicek it's up to the runtime team to update and release their boosters. Releasing booster does take quite some time (for Vert.x it takes about half a day without any interruptions). I will prioritize the task for Vert.x so you will get the booster early next week.

**Comment by piyush-garg** [comment]
So @cescoffier is taking care of Vert.x release, @Ladicek is taking care of WildFly Swarm, and I think @geoand is the right person for spring-boot booster. Correct me if I am wrong.

**Comment by geoand** [comment]
Myself and @metacosm are the right people for Spring Boot 😀

**Comment by geoand** [comment]
@metacosm Once you are done with the other changes to the booster poms, I will create PRs for updating the booster parent.

I would prefer we don't mix the two so we can be sure of the results

**Comment by cescoffier** [comment]
@geoand Have a look to dependabot - it opens the PR for you automatically.

**Comment by geoand** [comment]
@cescoffier Thanks for the tip! 
We tried it a few months ago but it was giving us a lot of false positives, so we ditched it. We should probably give it another look at some point.

Updating the boosters won't be too much of a problem since we have our [trusty scripts](https://github.com/snowdrop/booster-common/blob/master/for-all-boosters.sh) for that :)

**Comment by cescoffier** [comment]
So it needs a bit of tuning I agree (typically configure ignored artifacts). But when configured nicely, it's very convenient. Except that it's also a bit noisy... Imagine the number of PR raised when you have as many boosters as we do. But at least, it allows traceability and being sure to not miss some important updates.

**Comment by geoand** [comment]
Indeed, when we first checked it, we didn't have much time so we gave us quickly :).
Hopefully the second time around we'll be able to spend more time on it.

Thanks again for suggesting it!

**Comment by Ladicek** [comment]
@piyush1594 I am _not_ taking care of WildFly Swarm. I'm _just_ updating the community boosters to Thorntail v2, but if you want the product boosters updated and released as well (and I assume you do), please coordinate with @kenfinnigan.

**Comment by geoand** [comment]
@piyush1594 The boosters have been updated and will include the fix during our next release

**Comment by cescoffier** [comment]
Vert.x booster have been released, the catalog should be updated soon: 
https://github.com/fabric8-launcher/launcher-booster-catalog/pull/258
