### ISSUE TITLE
update Arquillian Cube to 1.18.0

### ISSUE THREAD

**Issue by Ladicek** [openshiftio/booster-parent#33]
1.18.0 allows this: https://github.com/arquillian/arquillian-cube/issues/1065

**Comment by cescoffier** [comment]
PR more than welcome.

It sounds like it's time to update a few things in the parent pom.

**Comment by Ladicek** [comment]
I'm in the middle of multiple things, but will provide a PR, sure.

**Comment by cescoffier** [comment]
Fixed by #34
