### ISSUE TITLE
Is this supposed to be an upstream project or Red Hat specific ? 

### ISSUE THREAD

**Issue by rhuss** [openshiftio/booster-parent#35]
I'm asking as this parent pom refers to the productised base images `registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2` for building images, which are not accessible freely and hence no images can be build without having access to the Red Hat registry.

I run into this as I just wanted to debug https://github.com/fabric8io/fabric8-maven-plugin/issues/1420 ...

**Comment by Ladicek** [comment]
So far, the image _is_ freely accessible, at least technically (and I'm pretty sure that as a Red Hat employee, you are entitled to use it :-) ). I know the subscription-only registry is the future and this registry will be discontinued, but we didn't yet have a conversation on how to handle this.

It would be great if we had an _actual_ upstream for the Red Hat OpenJDK image, and I've even seen some work being done about that. I'm pretty sure the Fabric8 image is not it.

**Comment by rhuss** [comment]
@Ladicek I'm talking with CE since probably late 2016 to get an upstream s2i image but there is none (although initially promised for June 2017). Currently, however it seems they are getting close to an upstream release, you might want to vote up https://issues.jboss.org/browse/CLOUD-2293 to get this out of the door. Although probably close, I wouldn't hold my breath.

> So far, the image _is_ freely accessible, at least technically

Hmm, at least with minishift it's not accessible when being on VPN (also not when used as imagestream):

```
$ eval $(minishift docker-env)
$ docker pull registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.2
Trying to pull repository registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift ...
Get https://registry.access.redhat.com/v1/_ping: dial tcp 10.4.204.31:443: i/o timeout
```

But this is very likely more an issue with Minishift accessing a VPN ...

**Comment by rhuss** [comment]
@Ladicek Thanks for the clarification !

**Comment by Ladicek** [comment]
Weird, I have never seen that kind of error, but then, I've never done `docker pull` in the `minishift docker-env` setting. I can pull the image normally, and OpenShift builds in my Minishift can pull the image as well.

**Comment by geoand** [comment]
Whenever I need the ImageStream in question for minishift, I just apply the `xpaas` addon. It seems to take care of whatever is needed to make it accessible

**Comment by quintesse** [comment]
> So far, the image is freely accessible, at least technically (and I'm pretty sure that as a Red Hat employee, you are entitled to use it :-) ).

Btw, this is not so theoretical, I've heard from "The Field" that they get these questions from customers too where the problem is that the can't legally create an image using those base images and push them to Docker Hub.

I have the feeling that the "conversation on how to handle this" is only going to happen once the theoretically not accessible becomes technically not accessible ;-)

**Comment by Ladicek** [comment]
That is unfortunately very likely :-)

**Comment by Ladicek** [comment]
I started an e-mail thread, with hope that it doesn't die before it's born :-)

**Comment by cescoffier** [comment]
My 2 cents on the title of this issue. This project is likely going to disappear at some point as it's main rationale (alignment between runtimes, validation of versions...) is not required anymore. The maturity of the used plugins and dependencies (FMP, Arquillian) has greatly improved making the updates smooth.

However, the specific question on the builder image... yeah... that's going to be tricky.
