### ISSUE TITLE
Downgrade to Maven 3.3.3?

### ISSUE THREAD

**Issue by quintesse** [openshiftio/booster-parent#9]
With the recent changes to the Launch project that has us looking at building the boosters using S2I instead of Jenkins it would be really helpful if we could downgrade the [required Maven version](https://github.com/openshiftio/booster-parent/blob/master/pom.xml#L38) from 3.3.9 to 3.3.3.

This is because Fabric8 already provides us with a working and tested Java+Maven S2I builder that we could use instead of having to create and maintain our own. But unfortunately they only support Maven 3.3.3.

(See [Docker Hub](https://hub.docker.com/r/fabric8/s2i-java/) and [GitHub](https://github.com/fabric8io-images/s2i))

**Comment by Ladicek** [comment]
The Red Hat Java S2I image that all boosters are using provides Maven 3.3.9, so I think this is a non-issue.

**Comment by quintesse** [comment]
The other option would be for the Fabric8 team to *upgrade* their Maven version of course. @gastaldi will ask them if that's a possibility.

**Comment by quintesse** [comment]
@Ladicek which S2I image is that? I'm not aware of any boosters using S2I?

**Comment by gastaldi** [comment]
Link to image: https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift

**Comment by cescoffier** [comment]
No, I recommend requiring Maven 3.5.x. This is required because of important changes inside Maven. Without, several plugins will behave differently.

**Comment by quintesse** [comment]
Using the RH image seems a valid option so I'll close this.

**Comment by quintesse** [comment]
Oh I actually didn't see your message before closing the issue @cescoffier . So are you saying that the RH OPenShift image might not be good enough either? It uses Maven 3.3.9

**Comment by cescoffier** [comment]
@quintesse well, it will just be nondeterministic ;-) I will work most of the time, but some plugins may not work (good case) or behave differently (nightmare to debug).

**Comment by kenfinnigan** [comment]
As an FYI, WF Swarm will likely not work without a Maven in 3.3.x range
